services:
  amadeus:
    build: .
    image: amadeus:latest
    container_name: amadeus
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./channels.json:/config/channels.json
